#!/usr/bin/env bash

if [ $# -ne 4 ]
then
	echo "Usage: $(basename $0) sourceDirs staticLibs libArgs binary"
	exit 1
fi

SOURCE_DIRS=$1
STATIC_LIBS=$2
LIB_ARGS=$3
BINARY=$4

SOURCE_FILES=$(find $SOURCE_DIRS -name "*.c")

mkdir -p $(dirname $BINARY)

clang $SOURCE_FILES $STATIC_LIBS $LIB_ARGS -o $BINARY \
	-Isource -Isource/c -std=c1x -D_POSIX_SOURCE -g -lm \
	-Werror -Weverything -Wno-unused-parameter -Wno-padded -Wno-c++-compat
