#!/usr/bin/env bash

if [[ $# -lt 1 || $# -gt 2 ]]
then
	echo "Usage: $(basename $0) username [commands]"
	exit 1
fi

USER=$1
COMMANDS=$2

ssh $USER@localhost \
	-i scripts/nomad/key/id_rsa \
	-o "BatchMode yes" \
	-p 2222 \
	$COMMANDS
