#!/usr/bin/env bash

if [ $# -ne 3 ]
then
	echo "Usage: $(basename $0) RUSTC CARGO SOURCE_DIR"
	exit 1
fi

RUSTC=$1
CARGO=$2
SOURCE_DIR=$3

export PATH=$(dirname $RUSTC):$PATH
export LD_LIBRARY_PATH=$(dirname $RUSTC)/../lib

(
	cd $SOURCE_DIR
	$CARGO build)
