#!/usr/bin/env bash

if [ $# -ne 4 ]
then
	echo "Usage: $(basename $0) rustc libArgs outputArgs sourceFile"
	exit 1
fi

RUSTC=$1
LIB_ARGS=$2
OUTPUT_ARGS=$3
SOURCE_FILE=$4

$RUSTC $LIB_ARGS $OUTPUT_ARGS $SOURCE_FILE
