#!/usr/bin/env bash

if [ $# -ne 3 ]
then
	echo "Usage: $(basename $0) <rustc> <lib-args> <source-file>"
	exit 1
fi

RUSTC=$1
LIB_ARGS=$2
SOURCE_FILE=$3

RUST_TEST=/tmp/rust-test-$RANDOM

mkdir -p $(dirname $RUST_TEST)

export LD_LIBRARY_PATH=$(dirname $RUSTC)/../lib

$RUSTC $LIB_ARGS --color=always --allow dead_code --test -o $RUST_TEST $SOURCE_FILE && $RUST_TEST --color=always
