#!/usr/bin/env bash

if [ $# -ne 2 ]
then
	echo "Usage: $(basename $0) libArgs sourceFile"
	exit 1
fi

LIB_ARGS=$1
SOURCE_FILE=$2

RUST_TEST=/tmp/rust-test-$RANDOM

mkdir -p $(dirname $RUST_TEST)

rustc $LIB_ARGS --test -o $RUST_TEST $SOURCE_FILE && $RUST_TEST
