#!/usr/bin/env bash

source project.conf

(echo "Cleaning client..."; cd $CLIENT_SOURCE; cargo clean)
(echo "Cleaning server..."; cd $SERVER_SOURCE; cargo clean)
(echo "Cleaning test_suite..."; cd $TESTS_SOURCE; cargo clean)
