#!/usr/bin/env bash

source project.conf

mkdir -p $OUTPUT_LIB_RUST

BINARY=$(pwd)/$DIST_BIN_DIR/$(basename $CLIENT_UI_BINARY)

if [ ! -f $OUTPUT_LIB_RUST/libfreetype* ]; then
    ./scripts/tasks/build-rust-freetype
fi

if [ ! -f $OUTPUT_LIB_RUST/libgl-* ]; then
    ./scripts/tasks/build-gl-rs
fi

if [ ! -f $OUTPUT_LIB/libglfw* ]; then
    ./scripts/tasks/build-glfw
fi

if [ ! -f $OUTPUT_LIB_RUST/libglfw* ]; then
    ./scripts/tasks/build-glfw-rs
fi

if [ ! -f $OUTPUT_LIB_RUST/libstb* ]; then
    ./scripts/tasks/build-rust-stb-image
fi

./scripts/tasks/build-client &&
./scripts/tasks/arrange-client $DIST_DIR &&
(cd $DIST_DIR && $BINARY localhost)
