#!/usr/bin/env bash

source project.conf

SOURCE_FILES=source/client/main.c
STATIC_LIBS=output/lib/libglfw.a
LIB_ARGS=-lGL
BINARY=$OUTPUT_DIR/vndf-client

./scripts/zwobot/zwobot-compile \
	$SOURCE_FILES $STATIC_LIBS $LIB_ARGS $BINARY &&
	./$BINARY $@
