#!/usr/bin/env bash

source project.conf

SOURCE_FILES=$(find $CORE_SERVICE_SOURCE -name "*.c")
HEADER_FILES=$(find $CORE_SERVICE_SOURCE -name "*.h")
RUST_FILES=$(find $CORE_SERVICE_SOURCE -name "*.rs")

function updateServer() {
	./scripts/tasks/build-core-service
	killall $CORE_SERVICE_NAME
	./$CORE_SERVICE_BINARY &
}

updateServer
while true
do
	inotifywait -qq -e modify $SOURCE_FILES $HEADER_FILES $RUST_FILES
	echo "Change detected."
	updateServer
done
