#!/usr/bin/env bash

source project.conf

FILES="\
source/upstart/vndf-server.conf \
$CORE_SERVICE_BINARY \
$CLIENT_BINARY \
source/vndf.de/index.html"

COMMANDS="
mkdir -p /opt/vndf
mv -f $CORE_SERVICE_NAME /opt/vndf
mv -f vndf-server.conf /etc/init
mv -f $CLIENT_NAME /srv/http/default
mv -f index.html /srv/http/default
restart --quiet $CORE_SERVICE_NAME"

./scripts/tasks/build-core-service
./scripts/tasks/build-client
./scripts/zwobot/zwobot-deploy "$FILES" "$COMMANDS" $SERVER_ADDRESS
