#!/usr/bin/env bash

source project.conf

export LD_LIBRARY_PATH=$RUST_LIB_PATH
export PATH=$(pwd)/source/rust/target:$RUST_PATH:$PATH

CONTAINER_DIR=output/docker/vndf

./scripts/init &&
rm -rf output &&
(
	cd source/rust
	cargo build) &&
./scripts/tasks/arrange-client &&
./scripts/tasks/package-client &&
mkdir -p $CONTAINER_DIR &&
cp source/docker/Dockerfile $CONTAINER_DIR &&
cp -r source/http $CONTAINER_DIR &&
cp -r source/nginx $CONTAINER_DIR &&
cp -r source/upstart $CONTAINER_DIR &&
cp $CLIENT_ARCHIVE $CONTAINER_DIR/http &&
cp -r output/bin $CONTAINER_DIR
