#!/usr/bin/env bash

source project.conf

# Prepare empty file for game service output.
TMP_OUTPUT=/tmp/vndf-game-service.out.tmp
rm -f $TMP_OUTPUT
touch $TMP_OUTPUT

# Build game service and, if successful, start it in the background.
cd $RUST_SOURCE/game_service_ng
cargo build &&
$GAME_SERVICE_BINARY_NG 34481 &> $TMP_OUTPUT &
GAME_SERVICE_PID=$!

# Wait until the game service has output anything. That means it's either ready
# or an error has occured.
while [ true ]
do
	if [ $(cat $TMP_OUTPUT | wc -l) == 1 ]
		then
			break
	fi
done

# Check if the game service is still running, exit if not.
if [ $(ps | grep $GAME_SERVICE_PID | wc -l) == 0 ]
	then
		echo "GAME SERVICE FAILED"
		echo ""
		cat $TMP_OUTPUT
		echo ""
		exit
fi

# Run the client
cd $RUST_SOURCE/client_ng
cargo run
