#!/usr/bin/env bash

source project.conf

# Prepare empty file for game service output.
TMP_OUTPUT=/tmp/vndf-game-service.out.tmp
rm -f $TMP_OUTPUT
touch $TMP_OUTPUT

# Build game service and, if successful, start it in the background.
cd $RUST_SOURCE/game_service_ng
cargo build &&
$GAME_SERVICE_BINARY &> $TMP_OUTPUT &
GAME_SERVICE_PID=$!

# Wait until the game service has output anything. That means it's either ready
# or an error has occured.
while [ true ]
do
	if [ $(cat $TMP_OUTPUT | wc -l) == 1 ]
		then
			break
	fi
done

# Check if the game service is still running, exit if not.
if [ $(ps | grep $GAME_SERVICE_PID | wc -l) == 0 ]
	then
		echo "GAME SERVICE FAILED"
		echo ""
		cat $TMP_OUTPUT
		echo ""
		exit
fi

# Clean up after the client is quit
function cleanup {
	# Reset the terminal
	stty echo
	stty icanon

	printf "Game Service Output:\n\n$(cat $TMP_OUTPUT)\n"
}
trap "cleanup" SIGINT

# Run the client
cd $CLIENT_SOURCE
cargo run
