#!/usr/bin/env bash

source project.conf

SOURCE_FILES="\
source/server/main.c \
source/server/net.c \
source/server/clients.c \
source/common/vec.c"

HEADER_FILES=$(find source/server source/common -name "*.h")

SERVER_NAME="vndf-server"
BINARY=$OUTPUT_DIR/$SERVER_NAME

function updateServer() {
	./scripts/zwobot/zwobot-compile "$SOURCE_FILES" "" "" $BINARY

	killall $SERVER_NAME

	./$BINARY &
	PID=$!
}

updateServer
while true
do
	inotifywait -qq -e modify $SOURCE_FILES $HEADER_FILES
	echo "Change detected."
	updateServer
done
