#!/usr/bin/env bash

source project.conf

SOURCE_FILES=$(find $GAME_SERVICE_SOURCE -name "*.rs")

./scripts/tasks/restart-server
while true
do
	inotifywait -qq -e modify $SOURCE_FILES
	echo -e "Change detected.\n\n\n"
	./scripts/tasks/restart-server
done
