#!/usr/bin/env bash

source project.conf

HOSTNAME="reineke"

FILES="source/nginx/default"

COMMANDS="
hostname $HOSTNAME
echo $HOSTNAME > /etc/hosts

apt-get -qq update
apt-get -qq upgrade

# Make sure apache is not included in the default install, as it conflicts with
# nginx.
apt-get -qq purge apache2 apache2-doc apache2-mpm-prefork apache2-utils \
	apache2.2-bin apache2.2-common

apt-get -qq install nginx
mv -f default /etc/nginx/sites-available/default
mkdir -p /srv/http/default
service nginx restart
"

./scripts/zwobot/zwobot-deploy "$FILES" "$COMMANDS" $SERVER_ADDRESS
