#!/usr/bin/env bash

source project.conf

SOURCE_FILES="tests/common/rbuf.c tests/common/stack.c"

for SPEC_FILE in $SOURCE_FILES
do
	SPEC_NAME="${SPEC_FILE%.*}"
	BINARY=$OUTPUT_DIR/$SPEC_NAME-test

	./scripts/zwobot/zwobot-compile \
		"$SPEC_FILE" "" "" $BINARY &&
		./$BINARY $@
done
