#!/usr/bin/env bash

source project.conf

./scripts/tasks/build-game-service &&
./scripts/tasks/build-client &&
./scripts/tools/test-rust \
	$RUSTC \
	"-L $OUTPUT_LIB_RUST" \
	tests/acceptance/main.rs
