#!/usr/bin/env bash

source project.conf

SPEC_FILES=$(find tests/ -name "*.c")
SOURCE_FILES="source/common/fix.c"

for SPEC_FILE in $SPEC_FILES
do
	SPEC_NAME="${SPEC_FILE%.*}"
	BINARY=$OUTPUT_DIR/$SPEC_NAME-test

	./scripts/zwobot/zwobot-compile \
		"$SPEC_FILE $SOURCE_FILES" "" "" $BINARY &&
		./$BINARY $@
done
