#!/usr/bin/env bash

source project.conf

(echo "Updating client_ng..."; cd $CLIENT_SOURCE; cargo update)
(echo "Updating game_service_ng..."; cd $GAME_SERVICE_SOURCE; cargo update)
(echo "Updating test_suite_ng..."; cd $RUST_SOURCE/test_suite_ng; cargo update)
