#!/usr/bin/env bash

source project.conf

START_SCRIPT_CONTENTS="\
#!/usr/bin/env bash
./bin/$(basename $CLIENT_BINARY) --address $SERVER_ADDRESS \
	1>> stdout.log \
	2>> stderr.log"
START_SCRIPT=$DIST_DIR/vndf

rm -rf $DIST_DIR

mkdir -p $DIST_DIR
mkdir -p $DIST_BIN_DIR

echo "$START_SCRIPT_CONTENTS" > $START_SCRIPT &&
chmod a+x $START_SCRIPT &&
cp $CLIENT_BINARY $DIST_BIN_DIR
