#!/usr/bin/env bash

source project.conf

mkdir -p $OUTPUT_LIB

function build-rust() {
	RUST_OUTPUT=$1
	RUST_SOURCE=$2

	rustc -L output/lib -o $RUST_OUTPUT $RUST_SOURCE
}

build-rust output/lib/common   source/rust/common/main.rs
build-rust output/lib/clients  source/rust/core-service/clients.rs
build-rust output/lib/net      source/rust/core-service/net.rs
build-rust output/lib/protocol source/rust/core-service/protocol.rs
build-rust output/lib/events   source/rust/core-service/events.rs

RUST_LIBS="\
$OUTPUT_LIB/libclients-9b872434-0.0.a \
$OUTPUT_LIB/libnet-5aef3837-0.0.a \
$OUTPUT_LIB/libprotocol-40062327-0.0.a \
$OUTPUT_LIB/libevents-d4a7d967-0.0.a"

./scripts/zwobot/zwobot-compile \
	"$CORE_SERVICE_SOURCE" \
	"$RUST_LIBS" \
	"-lm -lrt -ldl -lpthread -lstdc++" \
	$CORE_SERVICE_BINARY
