#!/usr/bin/env bash

source project.conf

mkdir -p $OUTPUT_LIB

function build-rust() {
	RUST_SOURCE=$1

	rustc -L $OUTPUT_LIB -o $OUTPUT_LIB/lib $RUST_SOURCE
}

build-rust source/rust/common/main.rs
build-rust source/rust/core-service/clients.rs
build-rust source/rust/core-service/net.rs
build-rust source/rust/core-service/protocol.rs
build-rust source/rust/core-service/events.rs

RUST_LIBS="\
$OUTPUT_LIB/libclients-9b872434-0.0.a \
$OUTPUT_LIB/libnet-5aef3837-0.0.a \
$OUTPUT_LIB/libprotocol-40062327-0.0.a \
$OUTPUT_LIB/libevents-d4a7d967-0.0.a"

./scripts/zwobot/zwobot-compile \
	"$CORE_SERVICE_SOURCE" \
	"$RUST_LIBS" \
	"-lm -lrt -ldl -lpthread -lstdc++" \
	$CORE_SERVICE_BINARY
