#!/usr/bin/env bash

source project.conf

export LD_LIBRARY_PATH=$(dirname $RUSTC)/../lib
export PATH=$(dirname $RUSTC):$PATH

RUSTFLAGS="-L $(pwd)/$OUTPUT_LIB"

mkdir -p $OUTPUT_LIB_RUST

(
	cd vendor/rust-freetype
	$CARGO build) &&
cp vendor/rust-freetype/target/*.rlib $OUTPUT_LIB_RUST
