#!/usr/bin/env bash

source project.conf

export LD_LIBRARY_PATH=$(dirname $RUSTC)/../lib
export PATH=$(dirname $RUSTC):$PATH

RUSTC_ARGS="-L $(pwd)/$OUTPUT_LIB"

(
	cd vendor/glfw-rs
	$CARGO build) &&
cp vendor/glfw-rs/target/*.rlib $OUTPUT_LIB_RUST
cp vendor/glfw-rs/target/*.a $OUTPUT_LIB
