#!/usr/bin/env bash

source project.conf

mkdir -p $OUTPUT_LIB_RUST
mkdir -p $(dirname $GAME_SERVICE_BINARY)

./scripts/tools/compile-rust \
	$RUSTC \
	"-L $OUTPUT_LIB_RUST" \
	"-o $GAME_SERVICE_BINARY" \
	source/rust/game-service/main.rs
