#!/usr/bin/env bash

source project.conf

export LD_LIBRARY_PATH=$(dirname $RUSTC)/../lib

RUSTFLAGS="-L $(pwd)/$OUTPUT_LIB"

(cd vendor/rust-freetype;
	./configure &&
	make clean &&
	make RUSTC=$RUSTC RUSTFLAGS="$RUSTFLAGS")
cp vendor/rust-freetype/*.rlib $OUTPUT_LIB_RUST
