#!/usr/bin/env bash

# This script requires the following dependencies to work:
# - cmake
# - xorg-dev


source project.conf

CURRENT_DIR=$(pwd)

mkdir -p $OUTPUT_LIB

cd vendor/glfw

cmake .
make
cp src/libglfw3.a $CURRENT_DIR/$OUTPUT_LIB

cd $CURRENT_DIR
