#!/usr/bin/env bash

source project.conf

mkdir -p $OUTPUT_LIB_RUST
mkdir -p $OUTPUT_BIN

if [ ! -f $OUTPUT_LIB/libfreetype.a ]; then
	echo "BUILDING freetype"
    ./scripts/tasks/build-freetype
fi
if [ ! -f $OUTPUT_LIB_RUST/libfreetype* ]; then
	echo "BUILDING rust-freetype"
    ./scripts/tasks/build-rust-freetype
fi
if [ ! -f $OUTPUT_LIB_RUST/libgl-* ]; then
	echo "BUILDING gl-rs"
    ./scripts/tasks/build-gl-rs
fi
if [ ! -f $OUTPUT_LIB/libglfw* ]; then
	echo "BUILDING glfw"
    ./scripts/tasks/build-glfw
fi
if [ ! -f $OUTPUT_LIB_RUST/libglfw* ]; then
	echo "BUILDING glfw-rs"
    ./scripts/tasks/build-glfw-rs
fi
if [ ! -f $OUTPUT_LIB_RUST/libstb* ]; then
	echo "BUILDING rust-stb-image"
    ./scripts/tasks/build-rust-stb-image
fi

./scripts/tools/compile-rust \
	$RUSTC \
	"-L $OUTPUT_LIB_RUST" \
	"--out-dir $OUTPUT_LIB_RUST" \
	source/rust/common/main.rs &&
./scripts/tools/compile-rust \
	$RUSTC \
	"-L $OUTPUT_LIB_RUST" \
	"-o $CLIENT_CORE_BINARY" \
	source/rust/client-core/main.rs &&
./scripts/tools/compile-rust \
	$RUSTC \
	"-L $OUTPUT_LIB_RUST -L $OUTPUT_LIB" \
	"-o $CLIENT_UI_BINARY" \
	source/rust/client-ui/main.rs &&
./scripts/tools/test-rust \
	$RUSTC \
	"-L $OUTPUT_LIB_RUST" \
	tests/unit/main.rs
