#!/usr/bin/env bash

source project.conf

mkdir -p $OUTPUT_LIB_RUST

./scripts/tools/compile-rust \
	$RUSTC \
	"-L $OUTPUT_LIB_RUST" \
	"--out-dir $OUTPUT_LIB_RUST" \
	source/rust/libcommon/lib.rs &&
./scripts/tools/compile-rust \
	$RUSTC \
	"-L $OUTPUT_LIB_RUST" \
	"--out-dir $OUTPUT_LIB_RUST" \
	source/rust/librustecs_macros/lib.rs
