#!/usr/bin/env bash

source project.conf

mkdir -p $OUTPUT_LIB

CURRENT_DIR=$(pwd)

cd vendor/freetype

./configure --without-png --without-zlib
make
cp objs/.libs/libfreetype.a $CURRENT_DIR/$OUTPUT_LIB
make clean
