#!/usr/bin/env bash

source project.conf

mkdir -p $OUTPUT_LIB_RUST

./scripts/tools/cargo-build \
	$RUSTC \
	$CARGO \
	$OUTPUT_LIB_RUST \
	source/rust/librustecs_macros &&
./scripts/tools/cargo-build \
	$RUSTC \
	$CARGO \
	$OUTPUT_LIB_RUST \
	source/rust/librustecs &&
./scripts/tools/compile-rust \
	$RUSTC \
	"-L $OUTPUT_LIB_RUST" \
	"--out-dir $OUTPUT_LIB_RUST" \
	source/rust/libcommon/lib.rs
