#!/usr/bin/env bash

source project.conf

rm -rf output &&
./scripts/tasks/run-tests &&
./scripts/tasks/build-vndf &&
./scripts/tasks/arrange-client &&
./scripts/tasks/package-client &&
mkdir -p $CONTAINER_DIR &&
cp source/docker/Dockerfile $CONTAINER_DIR &&
cp -r source/http/public/vndf.de $CONTAINER_DIR/http &&
cp -r source/nginx $CONTAINER_DIR &&
cp -r source/upstart $CONTAINER_DIR &&
cp $CLIENT_ARCHIVE $CONTAINER_DIR/http &&
cp $SERVER_BINARY $CONTAINER_DIR
