#!/usr/bin/env bash

source project.conf

export PATH=$RUST_TARGET:$PATH

rm -rf output &&
./scripts/init &&
./scripts/tasks/run-tests &&
./scripts/tasks/build-vndf &&
./scripts/tasks/arrange-client &&
./scripts/tasks/package-client &&
mkdir -p $CONTAINER_DIR &&
cp source/docker/Dockerfile $CONTAINER_DIR &&
cp -r source/http/public $CONTAINER_DIR/http &&
cp -r source/nginx $CONTAINER_DIR &&
cp -r source/upstart $CONTAINER_DIR &&
cp source/initial-state.json $CONTAINER_DIR &&
cp $CLIENT_ARCHIVE $CONTAINER_DIR/http &&
mkdir -p $CONTAINER_DIR/$(basename $RUST_TARGET) &&
cp -r $RUST_TARGET/vndf-* $CONTAINER_DIR/$(basename $RUST_TARGET)
