#!/usr/bin/env bash

source project.conf

export RUST_TEST_TASKS=1
export PATH=$(pwd)/output/bin:$PATH

./scripts/tasks/build-common &&
./scripts/tasks/build-game-service &&
./scripts/tasks/build-client &&
./scripts/tools/test-rust \
	$RUSTC \
	"-L $OUTPUT_LIB_RUST" \
	source/rust/tests/main.rs
